<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.leyou</groupId>
        <artifactId>leyou</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>ly-item</artifactId>
    <packaging>pom</packaging>

    <name>ly-item</name>
    <url>http://maven.apache.org</url>
    <modules>
        <module>ly-item-interface</module>
        <module>ly-item-service</module>
        <module>ly-common</module>
    </modules>

</project>
