server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_remote?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service # 应用名称
mybatis:
  type-aliases-package: com.leyou.userservice.pojo
#eureka:
#  client:
#    service-url: # EurekaServer地址
#      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
#  instance:
#    # 服务名:端口
#    instance-id: ${spring.application.name}:${server.port}
#    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
#    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
#    # 服务续约
#    lease-renewal-interval-in-seconds: 5      #心跳
#    lease-expiration-duration-in-seconds: 10  #过期

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找   当前这个服务，要把自己的【IP 地址】告诉 Eureka！
    lease-expiration-duration-in-seconds: 10  #过期 如果超过10秒没有发送心跳，EurekaServer就会认为该服务宕机，会从服务列表中移除，这两个值在生产环境不要修改，默认即可
    lease-renewal-interval-in-seconds: 5      #心跳  默认情况下每个5秒服务会向注册中心发送一次心跳，证明自己还活着